#controlplane
ansible_ssh_user: "ec2-user"
ansible_ssh_private_key_file: ~/.ssh/k8s_key
proxy_ssh_key: ~/.ssh/bastion_host_key
ansible_ssh_common_args: >-
  -o ProxyCommand="ssh 
  -o StrictHostKeyChecking=no
  -o UserKnownHostsFile=/dev/null
  -o ServerAliveInterval=5
  -W %h:%p
  -i {{ proxy_ssh_key }}
  -q {{ ansible_ssh_user }}@{{ hostvars[groups["_bastion_host"][0]]["public_ip_address"] }}"